/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:82234a52-c144-4eb2-982c-3b4990526739",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_b6WcPqNta",
    "aws_user_pools_web_client_id": "2ros8jl38mkc07nddd79ck9snf",
    "oauth": {}
};


export default awsmobile;
